# Generated by Django 2.2 on 2019-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190529_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
