# Generated by Django 2.2 on 2019-05-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20190529_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_titile',
            field=models.DateField(auto_now_add=True),
        ),
    ]
