# Generated by Django 2.2 on 2019-05-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_auto_20190530_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_titile',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
