# Generated by Django 2.2 on 2019-05-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0010_auto_20190530_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_titile',
            new_name='bpub_date',
        ),
    ]
