# Generated by Django 2.2 on 2019-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0011_auto_20190530_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('news_type', models.ManyToManyField(to='booktest.NewsType')),
            ],
        ),
    ]
