# Generated by Django 2.2 on 2019-05-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0012_news_newstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpolyeeBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpolyeeDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('empolyee_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.EmpolyeeBasicInfo')),
            ],
        ),
    ]
